### ISSUE TITLE
AttributeError: Can't get local object 'ZarrDataset.make_collate_fn.<locals>.<lambda>'

### ISSUE THREAD

**Issue by ningyuxin1999** [kr-colab/popgensbi_snakemake#55]
My laptop doesn't have GPU and I got the following issue while trying 
`snakemake --configfile workflow/config/AraTha_2epoch_cnn.yaml --snakefile workflow/training_workflow.smk`

I only changed the project path in the config file. Is it something happened before?

```
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/yuxinning/Projects/popgensbi_snakemake/AraTha_2epoch/AraTha_2epoch-cnn_extract-ExchangeableCNN_IN-1-500-sep exists and is not empty.

  | Name          | Type               | Params | Mode 
-------------------------------------------------------------
0 | embedding_net | ExchangeableCNN_IN | 41.0 K | train
1 | projection    | Linear             | 130    | train
2 | mseloss       | MSELoss            | 0      | train
-------------------------------------------------------------
41.1 K    Trainable params
0         Non-trainable params
41.1 K    Total params
0.164     Total estimated model params size (MB)
17        Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                                                                                      | 0/? [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/yuxinning/Projects/popgensbi_snakemake/.snakemake/scripts/tmp8q2tu4cq.train_embedding_network.py", line 152, in <module>
    trainer.fit(model=model, datamodule=datamodule)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 539, in fit
    call._call_and_handle_interrupt(
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/call.py", line 47, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 575, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 982, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1024, in _run_stage
    self._run_sanity_check()
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/trainer.py", line 1053, in _run_sanity_check
    val_loop.run()
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/loops/utilities.py", line 179, in _decorator
    return loop_run(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 122, in run
    self.reset()
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/loops/evaluation_loop.py", line 258, in reset
    iter(data_fetcher)  # creates the iterator inside the fetcher
    ^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 105, in __iter__
    super().__iter__()
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/loops/fetchers.py", line 52, in __iter__
    self.iterator = iter(self.combined_loader)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 351, in __iter__
    iter(iterator)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 155, in __iter__
    self._load_current_iterator()
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/utilities/combined_loader.py", line 173, in _load_current_iterator
    self.iterators = [iter(self.iterables[self._iterator_idx])]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 434, in __iter__
    self._iterator = self._get_iterator()
                     ^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 387, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1040, in __init__
    w.start()
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't get local object 'ZarrDataset.make_collate_fn.<locals>.<lambda>'
```

**Comment by nspope** [comment]
Huh, that's strange. From the trace it looks like issue with multiprocessing being used by torch.DataLoader. This hasn't happened to me before with linux-- what OS is your laptop @ningyuxin1999 , and what version of torch are you using? 

I guess we could turn the collate_fn lambda into a top-level function, and that might work.

**Comment by ningyuxin1999** [comment]
> Huh, that's strange. From the trace it looks like issue with multiprocessing being used by torch.DataLoader. This hasn't happened to me before with linux-- what OS is your laptop [@ningyuxin1999](https://github.com/ningyuxin1999) , and what version of torch are you using?
> 
> I guess we could turn the collate_fn lambda into a top-level function, and that might work.

Thank you, I have macOS and the following torch installed:

```
# packages in environment at /Users/yuxinning/miniconda3/envs/popgensbi_env:
#
# Name                    Version                   Build  Channel
pytorch                   2.2.2                  py3.12_0    pytorch
pytorch-lightning         2.5.0.post0              pypi_0    pypi
torchaudio                2.2.2                 py312_cpu    pytorch
torchmetrics              1.6.2                    pypi_0    pypi
torchvision               0.17.2                py312_cpu    pytorch
```

**Comment by nspope** [comment]
@ningyuxin1999 this is maybe fixed by #56 -- could you pull that down (see PR) and give it a shot? Thanks.

**Comment by ningyuxin1999** [comment]
> [@ningyuxin1999](https://github.com/ningyuxin1999) this is maybe fixed by [#56](https://github.com/kr-colab/popgensbi_snakemake/pull/56) -- could you pull that down (see PR) and give it a shot? Thanks.

Thank you! @nspope However it still doesn't work on my macOS. I got the same error after using the new top-level function.

I tried several things:

1. I used functions to pass function and this error disappeared:

```
def collate_fn_packed(data):
    return tuple(
        [
            torch.stack([d[0] for d in data]),
            pack_sequence([d[1] for d in data], enforce_sorted=False),
        ]
    )


def collate_fn_torch(data):
    return tuple(
        [
            torch.stack([d[0] for d in data]),
            torch.stack([d[1] for d in data]),
        ]
    )


def _make_collate_fn(packed_sequence: bool) -> Callable:
    return collate_fn_torch if not packed_sequence else collate_fn_packed


class ZarrDataset(Dataset):
    def __init__(
        self,
        zarr_path: str,
        split: str,
        use_cache: bool = True,
        packed_sequence: bool = False,
    ):
        self.root = zarr.open(zarr_path, mode="r")
        self.use_cache = use_cache
        self.indices = self.root[split][:]
        self.x_data = self.root.features
        self.x_shape = self.root.features_shape
        if "targets" in self.root:
            self.theta = Tensor(np.stack(self.root.targets[self.indices]))
        else:
            self.theta = None

        # If x is ragged use a PackedSequence to collate into batches
        self.packed_sequence = packed_sequence
        self.make_collate_fn = _make_collate_fn
        # TODO: rather than torch.stack, use pad_sequence so that
        # ragged arrays are handled seemlessly

        # Preload data into CPU memory if requested
        if self.use_cache:
            # TODO: make this multithreaded
            self.x_cache = [
                torch.from_numpy(self.x_data[i].reshape(*self.x_shape[i])).float()
                for i in self.indices
            ]

    def __getitem__(self, idx: int) -> tuple:
        if self.use_cache:
            # Use preloaded tensors
            x = self.x_cache[idx]
        else:
            # Load from zarr and return CPU tensors
            i = self.indices[idx]
            x = torch.from_numpy(self.x_data[i].reshape(*self.x_shape[i])).float()
        if self.theta is not None:
            return self.theta[idx], x
        else:
            # return empty tensor for theta
            return torch.empty(()), x

    def __len__(self) -> int:
        return len(self.indices)

```

2. A new error occurred when I ran 
`snakemake --configfile workflow/config/AraTha_2epoch_cnn.yaml --snakefile workflow/training_workflow.smk --jobs 1`

```
...
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/callbacks/model_checkpoint.py:654: Checkpoint directory /Users/yuxinning/Projects/popgensbi_snakemake/AraTha_2epoch/AraTha_2epoch-cnn_extract-ExchangeableCNN_IN-1-500-sep exists and is not empty.

  | Name          | Type               | Params | Mode 
-------------------------------------------------------------
0 | embedding_net | ExchangeableCNN_IN | 41.0 K | train
1 | projection    | Linear             | 130    | train
2 | mseloss       | MSELoss            | 0      | train
-------------------------------------------------------------
41.1 K    Trainable params
0         Non-trainable params
41.1 K    Total params
0.164     Total estimated model params size (MB)
17        Modules in train mode
0         Modules in eval mode
Sanity Checking: |                                                                                                                                          | 0/? [00:00<?, ?it/s]/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:425: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=7` in the `DataLoader` to improve performance.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 287, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yuxinning/Projects/popgensbi_snakemake/workflow/scripts/train_embedding_network.py", line 15, in <module>
    torch.manual_seed(snakemake.params.random_seed)
                      ^^^^^^^^^
NameError: name 'snakemake' is not defined
Traceback (most recent call last):
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/queues.py", line 113, in get
    if not self._poll(timeout):
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/connection.py", line 440, in _poll
    r = wait([self], timeout)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/multiprocessing/connection.py", line 1136, in wait
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuxinning/miniconda3/envs/popgensbi_env/lib/python3.12/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 51253) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
```

I'm trying to figure out how to fix this issue and I wonder if you have any clue of the cause. Thank you!

**Comment by nspope** [comment]
From https://docs.python.org/3/library/multiprocessing.html:

> Depending on the platform, [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) supports three ways to start a process. These start methods are
> 
>  spawn
> 
>  The parent process starts a fresh Python interpreter process. The child process will only inherit those resources necessary to run the process object’s [run()](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.run) method. In particular, unnecessary file descriptors and handles from the parent process will not be inherited. Starting a process using this method is rather slow compared to using fork or forkserver.
> 
>  Available on POSIX and Windows platforms. The default on Windows and macOS.
>  
>  fork
> 
>  The parent process uses [os.fork()](https://docs.python.org/3/library/os.html#os.fork) to fork the Python interpreter. The child process, when it begins, is effectively identical to the parent process. All resources of the parent are inherited by the child process. Note that safely forking a multithreaded process is problematic.
> 
>  Available on POSIX systems. Currently the default on POSIX except macOS.

So there's the problem -- macOS is spawning not forking processes. I'm not sure if there's a workaround here-- will look into it. I'm assuming you don't have access to a linux machine, @ningyuxin1999 ?

**Comment by ningyuxin1999** [comment]
> From https://docs.python.org/3/library/multiprocessing.html:
> 
> > Depending on the platform, [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) supports three ways to start a process. These start methods are
> > spawn
> > The parent process starts a fresh Python interpreter process. The child process will only inherit those resources necessary to run the process object’s [run()](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process.run) method. In particular, unnecessary file descriptors and handles from the parent process will not be inherited. Starting a process using this method is rather slow compared to using fork or forkserver.
> > Available on POSIX and Windows platforms. The default on Windows and macOS.
> > fork
> > The parent process uses [os.fork()](https://docs.python.org/3/library/os.html#os.fork) to fork the Python interpreter. The child process, when it begins, is effectively identical to the parent process. All resources of the parent are inherited by the child process. Note that safely forking a multithreaded process is problematic.
> > Available on POSIX systems. Currently the default on POSIX except macOS.
> 
> So there's the problem -- macOS is spawning not forking processes. I'm not sure what the workaround is here-- presumably we can change the behaviour to forking as macOS is POSIX, but it's torch that's setting all this up under the hood-- I will look into it (looks like there's some guidance here: https://pytorch.org/docs/stable/data.html#platform-specific-behaviors). I'm assuming you don't have access to a linux machine, [@ningyuxin1999](https://github.com/ningyuxin1999) ?

Thanks Nate! Building a Linux VM or accessing a linux server would be doable so there should be no problem. We could also leave these issues for now If we are not in a hurry to test or improve the pipeline adaptability for macOS.

**Comment by nspope** [comment]
I'm sure we can fix it, but I don't have access to MacOS at the moment, so it'll take some back and forth. In the meantime, if you have access to a linux cluster that'd be the way to go.
